# Generated by Django 3.2.16 on 2023-03-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worldmember',
            old_name='members',
            new_name='user',
        ),
    ]
