# Generated by Django 3.2.19 on 2023-06-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds_app', '0003_alter_world_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
