# Generated by Django 3.2.19 on 2023-05-05 20:41

from django.db import migrations, models
from django.template.defaultfilters import slugify


def populate_profile_slugs(apps, schema_editor):
    Profile = apps.get_model("user_app", "Profile")

    for profile in Profile.objects.iterator():
        # Save to set the slug
        profile.slug = slugify(profile.user.username)
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='slug', blank=True),
            preserve_default=False,
        ),
        migrations.RunPython(populate_profile_slugs,
                             reverse_code=migrations.RunPython.noop)
    ]
