# Generated by Django 3.2.16 on 2023-02-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_character_setting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='creator',
            new_name='owner',
        ),
    ]
