# Generated by Django 3.2.16 on 2023-02-19 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0003_auto_20230219_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='members',
            field=models.ManyToManyField(default=(), related_name='_user_app_setting_members_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
