# Generated by Django 3.2.15 on 2022-08-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('height', models.FloatField(verbose_name='height (m)')),
                ('weight', models.FloatField(verbose_name='weight (kg)')),
                ('description', models.TextField()),
                ('evolves_by', models.TextField(blank=True, null=True)),
                ('base_strength', models.IntegerField()),
                ('base_dexterity', models.IntegerField()),
                ('base_vitality', models.IntegerField()),
                ('base_special', models.IntegerField()),
                ('base_insight', models.IntegerField()),
                ('base_hp', models.IntegerField(verbose_name='base hit points')),
                ('max_strength', models.IntegerField()),
                ('max_dexterity', models.IntegerField()),
                ('max_vitality', models.IntegerField()),
                ('max_special', models.IntegerField()),
                ('max_insight', models.IntegerField()),
                ('abilities', models.ManyToManyField(related_name='species', to='pokerole_app.Ability')),
                ('evolutions', models.ManyToManyField(blank=True, null=True, related_name='_pokerole_app_pokemonspecies_evolutions_+', to='pokerole_app.PokemonSpecies')),
                ('moveset', models.ManyToManyField(related_name='species', to='pokerole_app.Move')),
                ('types', models.ManyToManyField(related_name='species', to='pokerole_app.Type')),
            ],
        ),
    ]
