# Generated by Django 4.1 on 2022-08-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokerole_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
