# Generated by Django 3.2.15 on 2022-08-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerole_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonspecies',
            name='variant',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='abilities',
            field=models.ManyToManyField(blank=True, related_name='species', to='pokerole_app.Ability'),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='base_dexterity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='base_hp',
            field=models.PositiveIntegerField(verbose_name='base hit points'),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='base_insight',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='base_special',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='base_strength',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='base_vitality',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='evolutions',
            field=models.ManyToManyField(blank=True, related_name='_pokerole_app_pokemonspecies_evolutions_+', to='pokerole_app.PokemonSpecies'),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='evolves_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='max_dexterity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='max_insight',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='max_special',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='max_strength',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='max_vitality',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='moveset',
            field=models.ManyToManyField(blank=True, related_name='species', to='pokerole_app.Move'),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='species', to='pokerole_app.Type'),
        ),
    ]
