# Generated by Django 3.2.16 on 2023-02-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokerole_app', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
