# Generated by Django 3.2.15 on 2022-08-13 21:08

from django.db import migrations, models


def create_types(apps, schema_editor):
    Type = apps.get_model('pokerole_app', 'Type')
    types = ('normal', 'bug', 'dark', 'dragon', 'electric', 'fairy', 'fight', 'fire', 'flying',
             'ghost', 'grass', 'ground', 'ice', 'poison', 'psychic', 'rock', 'steel', 'water')
    for type in types:
        Type(name=type.capitalize()).save()


def add_weaknesses(apps, schema_editor):
    Type = apps.get_model('pokerole_app', 'Type')
    weaknesses = {
        'normal': ('fight',),
        'bug': ('fire', 'flying', 'rock'),
        'dark': ('bug', 'fairy', 'fight'),
        'dragon': ('dragon', 'fairy', 'ice'),
        'electric': ('ground',),
        'fairy': ('poison', 'steel'),
        'fight': ('fairy', 'flying', 'psychic'),
        'fire': ('ground', 'rock', 'water'),
        'flying': ('electric', 'ice', 'rock'),
        'ghost': ('dark', 'ghost'),
        'grass': ('bug', 'fire', 'flying', 'ice', 'poison'),
        'ground': ('grass', 'ice', 'water'),
        'ice': ('fight', 'fire', 'rock', 'steel'),
        'poison': ('ground', 'psychic'),
        'psychic': ('bug', 'dark', 'ghost'),
        'rock': ('grass', 'ground', 'fight', 'steel', 'water'),
        'steel': ('fight', 'fire', 'ground'),
        'water': ('electric', 'grass')
    }
    for key in weaknesses:
        type = Type.objects.get(name=key.capitalize())
        for weakness in weaknesses[key]:
            weakness_object = Type.objects.get(name=weakness.capitalize())
            type.weaknesses.add(weakness_object)


def add_resistances(apps, schema_editor):
    Type = apps.get_model('pokerole_app', 'Type')
    resistances = {
        'bug': ('fight', 'grass', 'ground'),
        'dark': ('dark', 'ghost'),
        'dragon': ('electric', 'fire', 'grass', 'water'),
        'electric': ('electric', 'flying', 'steel'),
        'fairy': ('bug', 'dark', 'fight'),
        'fight': ('bug', 'dark', 'rock'),
        'fire': ('bug', 'fairy', 'fire', 'grass', 'ice', 'steel'),
        'flying': ('bug', 'fight', 'grass'),
        'ghost': ('bug', 'poison'),
        'grass': ('electric', 'grass', 'ground', 'water'),
        'ground': ('poison', 'rock'),
        'ice': ('ice',),
        'poison': ('bug', 'fairy', 'fight', 'grass', 'poison'),
        'psychic': ('fight', 'psychic'),
        'rock': ('fire', 'flying', 'normal', 'poison'),
        'steel': ('bug', 'dragon', 'flying', 'fairy', 'grass', 'ice', 'normal', 'psychic', 'rock', 'steel'),
        'water': ('fire', 'ice', 'steel', 'water')
    }
    for key in resistances:
        type = Type.objects.get(name=key.capitalize())
        for resistance in resistances[key]:
            resistance_object = Type.objects.get(name=resistance.capitalize())
            type.resistances.add(resistance_object)


def add_immunities(apps, schema_editor):
    Type = apps.get_model('pokerole_app', 'Type')
    immunities = {
        'normal': ('ghost',),
        'dark': ('psychic',),
        'fairy': ('dragon',),
        'flying': ('ground',),
        'ghost': ('fight', 'normal'),
        'ground': ('electric',),
        'steel': ('poison',)
    }
    for key in immunities:
        type = Type.objects.get(name=key.capitalize())
        for immunity in immunities[key]:
            immunity_object = Type.objects.get(name=immunity.capitalize())
            type.immunities.add(immunity_object)


class Migration(migrations.Migration):

    dependencies = [
        ('pokerole_app', '0003_auto_20220811_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='immunities',
            field=models.ManyToManyField(
                blank=True, related_name='no_effect', to='pokerole_app.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='resistances',
            field=models.ManyToManyField(
                blank=True, related_name='not_effective', to='pokerole_app.Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='weaknesses',
            field=models.ManyToManyField(
                blank=True, related_name='super_effective', to='pokerole_app.Type'),
        ),
        migrations.RunPython(create_types, migrations.RunPython.noop),
        migrations.RunPython(add_weaknesses, migrations.RunPython.noop),
        migrations.RunPython(add_resistances, migrations.RunPython.noop),
        migrations.RunPython(add_immunities, migrations.RunPython.noop),
    ]
