# Generated by Django 3.2.15 on 2022-08-19 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokerole_app', '0004_expand_type_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokedex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PokedexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('rarity', models.CharField(blank=True, choices=[('Legendary', 'Legendary'), ('Very_rare', 'Very Rare'), ('Rare', 'Rare'), ('Uncommon', 'Uncommon'), ('Common', 'Common')], max_length=30, null=True)),
                ('pokedex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerole_app.pokedex')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='pokerole_app.pokemonspecies')),
            ],
        ),
        migrations.AddField(
            model_name='pokedex',
            name='species',
            field=models.ManyToManyField(through='pokerole_app.PokedexEntry', to='pokerole_app.PokemonSpecies'),
        ),
    ]
