# Generated by Django 3.2.15 on 2022-10-03 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokerole_app', '0005_pokedex_and_entry_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='effect',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='ability',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='move',
            name='category',
            field=models.CharField(blank=True, choices=[('PH', 'Physical'), ('SP', 'Special'), ('SU', 'Support')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='damage_modifier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='damage_stat',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='move',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='move',
            name='power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='primary_accuracy',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='ranged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='move',
            name='reduced_accuracy',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='secondary_accuracy',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='pokerole_app.type'),
        ),
    ]
