# Generated by Django 3.2.16 on 2023-02-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerole_app', '0013_pokedex_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokedexentry',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pokedexentry',
            name='rarity',
            field=models.CharField(blank=True, choices=[('legendary', 'Legendary'), ('very_rare', 'Very Rare'), ('rare', 'Rare'), ('uncommon', 'Uncommon'), ('common', 'Common')], max_length=30, null=True),
        ),
    ]
