# Generated by Django 3.2.19 on 2023-05-29 17:39

from django.db import migrations, models


def change_learned_ranks_to_integers(apps, schema_editor):
    MoveSet = apps.get_model("pokerole_app", "MoveSet")

    translation = {"Starter": 0, "Beginner": 1, "Amateur": 2,
                   "Ace": 3, "Pro": 4, "Master": 5, "Champion": 6}

    for move_set in MoveSet.objects.iterator():
        move_set.learned = str(translation[move_set.learned])
        move_set.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pokerole_app', '0015_pokedex_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='move',
            options={'ordering': ['name']},
        ),
        migrations.RunPython(change_learned_ranks_to_integers, reverse_code=migrations.RunPython),
        migrations.AlterField(
            model_name='moveset',
            name='learned',
            field=models.PositiveIntegerField(choices=[(0, 'Starter'), (1, 'Beginner'), (
                2, 'Amateur'), (3, 'Ace'), (4, 'Pro'), (5, 'Master'), (6, 'Champion')], default=0),
        ),
    ]
